// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBViBWFMOpb7uNSKaw0RfRAYPgEb3T2_gU',
    appId: '1:495071690051:web:1d4bb843c824e64b6143f6',
    messagingSenderId: '495071690051',
    projectId: 'mobile2025-efd4e',
    authDomain: 'mobile2025-efd4e.firebaseapp.com',
    storageBucket: 'mobile2025-efd4e.firebasestorage.app',
    measurementId: 'G-TZY80CE0MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuVKGEiRnsSyNoeOIrkXF6doHiCVic4E0',
    appId: '1:495071690051:android:a297269f8ed3a8ac6143f6',
    messagingSenderId: '495071690051',
    projectId: 'mobile2025-efd4e',
    storageBucket: 'mobile2025-efd4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPvW2oRo6Fk0wV-8xZZfH-QslAG52jAxQ',
    appId: '1:495071690051:ios:9f8dfafb2af98c9d6143f6',
    messagingSenderId: '495071690051',
    projectId: 'mobile2025-efd4e',
    storageBucket: 'mobile2025-efd4e.firebasestorage.app',
    iosBundleId: 'com.example.mobile25',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPvW2oRo6Fk0wV-8xZZfH-QslAG52jAxQ',
    appId: '1:495071690051:ios:9f8dfafb2af98c9d6143f6',
    messagingSenderId: '495071690051',
    projectId: 'mobile2025-efd4e',
    storageBucket: 'mobile2025-efd4e.firebasestorage.app',
    iosBundleId: 'com.example.mobile25',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBViBWFMOpb7uNSKaw0RfRAYPgEb3T2_gU',
    appId: '1:495071690051:web:d261dbd6174ea6a36143f6',
    messagingSenderId: '495071690051',
    projectId: 'mobile2025-efd4e',
    authDomain: 'mobile2025-efd4e.firebaseapp.com',
    storageBucket: 'mobile2025-efd4e.firebasestorage.app',
    measurementId: 'G-CX5LXC2SPS',
  );
}
